version: "3.9"  # optional since v1.27.0
services:
  jupyterlab:
    container_name: jupyterlab
    build: 
        context: .
    image: jupyter/base-notebook-explorer:latest
    ports:
      - "9999:8888"
    volumes:
      - ".:/home/jovyan/work"
